DELETE FROM RENTIT.ACCOUNT;
DELETE FROM RENTIT.RESERV_STATUS;

INSERT INTO RENTIT.ACCOUNT (ID, ACCOUNT_FUNCTION, EMAIL, LOGIN,
                             NAME, PASSWORD, PHONE, SURNAME, VERSION) 
VALUES (1, 'admin', 'test@test.pl', 'admin', 'Przemysław',
         'jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=', '111111111', 'Przysło', 1);

INSERT INTO RENTIT.RESERV_STATUS (ID, RESERVATION_STATUS_NAME, VERSION) 
VALUES (1, 'Zarezerwowany', 1);

INSERT INTO RENTIT.RESERV_STATUS (ID, RESERVATION_STATUS_NAME, VERSION) 
VALUES (2, 'Rezerwacja odrzucona', 1);

INSERT INTO RENTIT.RESERV_STATUS (ID, RESERVATION_STATUS_NAME, VERSION) 
VALUES (3, 'Rezerwacja zaakceptowana', 1);

INSERT INTO RENTIT.RESERV_STATUS (ID, RESERVATION_STATUS_NAME, VERSION) 
VALUES (4, 'Rezerwacja zaakceptowana / zmodyfikowana', 1);

INSERT INTO RENTIT.RESERV_STATUS (ID, RESERVATION_STATUS_NAME, VERSION) 
VALUES (5, 'Rezerwacja ZAKOŃCZONA', 1);